name: Compile libqalculate

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - libqalculate-compile

env:
    GMP_VERSION: 6.3.0
    MPFR_VERSION: 4.2.1
    LIBXML2_VERSION: 2.9.12
    LIBQALCULATE_VERSION: 5.2.0
    EM_VERSION: 3.1.67
    EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v4

            - name: Setup dependency cache
              id: cache-dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ~/opt/lib
                      ~/opt/include
                  key: a${{env.LIBQALCULATE_VERSION}}-gmp${{env.GMP_VERSION}}-mpfr${{env.MPFR_VERSION}}-libxml2${{env.LIBXML2_VERSION}}-em${{env.EM_VERSION}}-${{ runner.os }}

            - name: Setup emsdk cache
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              id: cache-system-libraries
              uses: actions/cache@v2
              with:
                  path: ${{env.EM_CACHE_FOLDER}}
                  key: ${{env.EM_VERSION}}-${{ runner.os }}

            - name: Setup emsdk
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              uses: mymindstorm/setup-emsdk@v14
              with:
                  version: ${{env.EM_VERSION}}
                  actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

            - name: Setup dependencies
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: |
                  chmod +x ./.github/workflows/prepare-libqalculate.sh
                  ./.github/workflows/prepare-libqalculate.sh
