name: Compile libqalculate

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - libqalculate-compile

env:
    GMP_VERSION: 6.3.0
    MPFR_VERSION: 4.2.1
    LIBXML2_VERSION: 2.9.12
    LIBQALCULATE_VERSION: 5.2.0
    EM_VERSION: 3.1.67
    EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v4

            - name: Setup cache
              id: cache-system-libraries
              uses: actions/cache@v2
              with:
                  path: ${{env.EM_CACHE_FOLDER}}
                  key: ${{env.EM_VERSION}}-${{ runner.os }}

            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@v14
              with:
                  version: ${{env.EM_VERSION}}
                  actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

            - name: Setup dependencies
              run: |
                  sudo apt install build-essential lzip binutils autoconf intltool libtool automake lbzip2 lzip
                  mkdir -p ~/opt/src
                  cd ~/opt/src

                  wget https://ftp.gnu.org/gnu/gmp/gmp-${GMP_VERSION}.tar.lz -O gmp.tar.lz
                  tar xf gmp.tar.lz
                  cd gmp
                  emconfigure ./configure --disable-assembly --host none --enable-cxx --prefix=${HOME}/opt # no, the "none" host is not obsolete.
                  make
                  make install
                  cd ..

                  wget https://ftp.gnu.org/gnu/mpfr/mpfr-${MPFR_VERSION}.tar.xz -O mpfr.tar.xz
                  # wget https://www.mpfr.org/mpfr-current/allpatches # if available
                  tar xf mpfr.tar.xz
                  cd mpfr
                  emconfigure ./configure --prefix=${HOME}/opt --with-gmp=${HOME}/opt
                  make
                  make install
                  cd ..

                  wget http://xmlsoft.org/download/libxml2-${LIBXML2_VERSION}.tar.gz -O libxml2.tar.gz
                  tar xf libxml2.tar.gz 
                  cd libxml2
                  emconfigure ./configure --prefix=${HOME}/opt --disable-shared
                  make
                  make install
                  ln -s ${HOME}/opt/include/libxml2/libxml ${HOME}/opt/include/libxml
                  cd ..

                  wget https://github.com/Qalculate/libqalculate/archive/refs/tags/v5.2.0.tar.gz -O libqalculate.tar.gz
                  tar xf libqalculate.tar.gz
                  cd libqalculate
                  # the following command is supposed to fail, since it's also running the configure script
                  ./autogen.sh || true
                  sed -i 's/PKG_CHECK_MODULES(LIBCURL, libcurl)/#PKG_CHECK_MODULES(LIBCURL, libcurl)/' configure
                  sed -i 's/PKG_CHECK_MODULES(ICU, icu-uc)/#PKG_CHECK_MODULES(ICU, icu-uc)/' configure
                  sed -i 's/PKG_CHECK_MODULES(LIBXML, libxml-2.0/#PKG_CHECK_MODULES(LIBXML, libxml-2.0/' configure
                  sed -i 's/#define HAVE_LIBCURL 1//' configure
                  sed -i 's/#define HAVE_ICU 1//' configure
                  sed -i 's/#define HAVE_PIPE2 1/#define HAVE_PIPE2 0/' configure
                  emconfigure ./configure --prefix=${HOME}/opt CPPFLAGS=-I${HOME}/opt/include LDFLAGS="-L${HOME}/opt/lib -lxml2" --without-libcurl --enable-compiled-definitions --disable-nls --disable-shared
                  make
                  make install
                  cd ..
